sonar.projectKey=MafeLopezQuintana_credit-risk-mflq
sonar.organization=mafelopezquintana

sonar.sources=mlops_pipeline/src
sonar.tests=mlops_pipeline/tests
sonar.python.version=3.13

sonar.exclusions=**/*.ipynb,**/venv/**,**/creditrisk-venv/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=mlops_pipeline/src/app_streamlit.py